extra0: .asciiz "Isto e uma mensagem de enfase(enfase?)"
extra1: .asciiz "Assembly <3"
extra2: .asciiz "Saudades professor Guilherme ;-;"
extra3: .asciiz "Joguem Touhou. E uma ordem."
extra4: .asciiz "Existe tres tipos de programacao: programacao para embarcados, programacao para sistemas e programacao para as provas do Marilton."
extra5: .asciiz "Entenderam, todo mundo entendeu? Entenderam, sim ou nao?"
extra6: .asciiz "Se o prof. Mauricio virar presidente, o real vai se chamar pila. Nao pera..."
extra7: .asciiz "Imagina um marmanjo falando 'Fredericoo~' ou 'Vivii~'. Imaginou?"
extra8: .asciiz "Ir a pe para o Anglo nem e tao ruim!"
extra9: .asciiz "Todos os dias depois da aula agora eu irei pra Cotada/CEng, e muito gostoso estudar la s2"
extra10: .asciiz "o jojojojojojojojojojojojojojojojojojojojojojo"
extra11: .asciiz "Professor Lulu ou professora Lulu?"
extra12: .asciiz "Tem que ser muito doente ou um engenheiro pra gostar de Calculo..."
extra13: .asciiz "'Lindo da tia, beijos.'"
extra14: .asciiz "Sabe por que C++ nao deu certo? Porque o criador nao chamou de C++;, ai quando tentaram usar, nao compilou."
extra15: .asciiz "Na porta de um dos boxes do banheiro do corredor do primeiro andar tem uma mensagem honesta."
extra16: .asciiz "Tem uma bruxa moe na turma da Engenharia deste ano, e ela e fofa. Protejam-a!"
extra17: .asciiz "Tambem comemorei o Halloween este ano, sai de casa 6 da manha naquela quarta-feira so pra ir ver uma bruxa"
extra18: .asciiz "Aquele momento em que descobrem as lolis na casa do aluno de Computacao~"
extra19: .asciiz "Foda ser orelha..."
extra20: .asciiz "Sera que o prof. Mauricio entende bem de pilha?"